### ISSUE TITLE
[Issue]: Paxels not breaking stone

### ISSUE THREAD

**Issue by aulttye** [The-Nexus-Project/Limitless-6#77] opened 2023-04-26 19:00 UTC
### What happened?

Paxels from mekanism are not registering as pickaxe tools. 

### Pack Version

Version: 1.22.0

### To Reproduce

1. Multiple players how my server are showing the same issue

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment] 2023-04-26 19:12
Hey, thanks for report.

I can't reproduce this issue they work as normal, and can mine stone on this side.
![bild](https://user-images.githubusercontent.com/26634554/234678984-b3c9e17e-3792-4cf4-8807-0a32e48feb70.png)

**Comment by aulttye** [comment] 2023-04-26 19:40
Thank you for the quick reply. I will talk with the players to see how they did it.

**Comment by Gbergz** [comment] 2023-04-26 19:41
You are not the first to report this, however I can't seem to reproduce it as seen above.

**Comment by aulttye** [comment] 2023-04-26 20:57
Looks like it just Paxels. Mystical ag, mekanism, and pickle tweaks. Except silent gear for some reason. 
Only server side from the server download.

**Comment by aulttye** [comment] 2023-04-26 22:21
I just tested on a newly downloaded server file from curseforge. 
It works on client but on server it doesn't.

![2023-04-26_18 16 49](https://user-images.githubusercontent.com/1280984/234715430-aaab3e2e-c012-4ca4-981e-d73f5e17465d.png)
![2023-04-26_18 16 52](https://user-images.githubusercontent.com/1280984/234715431-d7b2722d-c426-4a62-8960-6bb75abf57e6.png)
![2023-04-26_18 16 52_2](https://user-images.githubusercontent.com/1280984/234715433-678cc4a3-e097-4259-a157-55d0325b4aaa.png)

**Comment by Gbergz** [comment] 2023-04-27 13:55
Interesting, leaving this up for visibilty. Trying to find and fix the issue.

**Comment by Gbergz** [comment] 2023-04-27 19:50
Closing in favor of this one https://github.com/The-Nexus-Project/Limitless-6/issues/78 updates will be posted in it.

**Closed by Gbergz** 2023-04-27 19:50 UTC
Labels: issue
