### ISSUE TITLE
[Issue]: Multiple tools do not work

### ISSUE THREAD

**Issue by agadros** [The-Nexus-Project/Limitless-6#78] opened 2023-04-27 18:48 UTC
### What happened?

1. Axes. Tried all vanilla axes and they do not work on typical wood items, including oak logs, oak planks, vanilla crafting tables and vanilla chests. I tried some modded axes including Livingwood Axe (AIOT Botania). Certus Quartz Axe (AE2), Brimsteel Axe (Blaze Gear), Amethyst Axe (Cyclic), Steel Axe (Immersive Engineering) and Refined Obsidian Axe (Mekanism: Tools). Of these, only the Brimsteel Axe mined a block faster than bare hand does. Efficiency does affect the Brimsteel Axe.

2. Hoes. All vanilla hoes seem to not mine their respective blocks faster. Tried on Hay Bale, Nether Wart Block and Shroomlight. Brimsteel hoe does not mine these faster than bare hand does (I mention this since the Brimsteel Axe works). Hoes do still make farmland. Tested on all vanilla hoes and Brimsteel Hoe (Blaze Gear).

3. Paxels. Doesn't matter what their origin mod is. They seem to not work at all (dirt/sand/gravel, stone and wood blocks). Efficiency enchantment does not affect their mining speed. 

4. Other tools. Shovels and pickaxes seem to work fine. Of course, all tool issues may be more expansive than what I tested.

### Pack Version

Version: 1.22.0

### To Reproduce

No special armor, item modifiers (Apotheosis) or enchantments required. No player status effects or curios items used. 

Modpack was loaded from CurseForge launcher (not downloaded manually). It was not modified from the original CurseForge download.

Just open a single player survival world and attempt to use any of the tools written in the issue description, on the specified blocks.

Note: this was tested on both a world created using this new pack version (1.22.0) and on a world created with a previous pack version (1.21.2, I believe). Axes, Hoes and Paxels seem to work fine on 1.21.2 worlds, but not on new ones.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by agadros** [comment] 2023-04-27 19:20
Unfortunate. Thank you for looking into it. Small update regarding this issue though. I closed and re-opened my test world and, at least for the paxels, the issue seemed to have gone away. I've no idea what changed.

**Comment by nickalbrecht** [comment] 2023-04-28 06:22
v1.22.0
I ran into this when I installed the pack for the first time a couple days ago, surprised it's not something more people are experiencing? The other symptom I have noticed is that none of the woodblocks show the Axe icon in the tooltip to show that they are appropriate tools, the way Pickaxe icon does show up for stone.

**Comment by Gbergz** [comment] 2023-04-28 08:03
It also seems atleast to me to be a server sided only issue. Can't get it to be reproduced in Singleplayer.

**Comment by Gbergz** [comment] 2023-04-28 12:05
Seems to be fixed after I updated mods on my Indev client see: https://streamable.com/5txyyl

Gotta test in multiplayer too though to be sure.

**Comment by nickalbrecht** [comment] 2023-04-29 03:55
I was experiencing it in Single Player, but I'll let you know to verify one way or the other when the next version is available

**Comment by nickalbrecht** [comment] 2023-04-30 23:15
Updated today, can confirm it appears to be fixed

**Comment by Gbergz** [comment] 2023-04-30 23:19
Awesome, thanks for replies and initial report. Closing!

**Closed by Gbergz** 2023-04-30 23:19 UTC
Labels: issue, fixed: next update
